enum Actions {
  ADD_PROJECT = "ADD_PROJECT",
  MARK_COMPLETE = "MARK_COMPLETE",
  MARK_INCOMPLETE = "MARK_INCOMPLETE",
  ADD_TIME = "ADD_TIME",
  SORT_BY_DEADLINE = `SORT:DEADLINE`,
  SORT_BY_CREATION_DATE = `SORT:CREATION_DATE`,
}

export default Actions;
